HOSTS:
  ubuntu-1210-x64:
    roles:
      - master
    platform: ubuntu-12.10-x64
    image: ubuntu_1210_curl_rubygems
    hypervisor: docker
CONFIG:
  type: foss

---
That's a YAML document marker, we're safe to talk here.

The ubuntu_1210_curl_rubygems image is built like so:

docker build -t ubuntu_1210_curl_rubygems - <<EOF
FROM ubuntu:12.10
RUN apt-get update
RUN apt-get -y install curl rubygems
EOF

It's quite the timesaver

    $ time bundle exec rspec spec/acceptance
    [not many tests run]

    Finished in 8.72 seconds
    2 examples, 0 failures

    real    0m45.026s
    user    0m1.653s
    sys     0m0.256s

For more timesaving you might want to pre-compile puppet in too
